apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-bot
  namespace: cloudshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-bot
  namespace: cloudshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-bot
  template:
    metadata:
      labels:
        app: aiops-bot
    spec:
      serviceAccountName: aiops-bot
      containers:
        - name: aiops-bot
          image: 420828412451.dkr.ecr.us-east-1.amazonaws.com/cloudshop-aiops:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: CLUSTER_NAME
              value: "cloudshop-lite"
            - name: CW_LOG_GROUP
              value: "/aws/eks/cloudshop-lite/cluster"  
          ports:
            - containerPort: 5100   # ðŸ‘ˆ matches Flask logs
---
apiVersion: v1
kind: Service
metadata:
  name: aiops-bot-service
  namespace: cloudshop
spec:
  selector:
    app: aiops-bot
  ports:
    - name: http
      port: 5100          # ðŸ‘ˆ service port
      targetPort: 5100    # ðŸ‘ˆ forwards to pod port 5100
      protocol: TCP
